book:
  info: "C:\\Users\\Kikki\\AppData\\Roaming\\Reader\\book_info.json"
  dir: "C:\\Users\\Kikki\\AppData\\Roaming\\Reader\\book"
  cover: "C:\\Users\\Kikki\\AppData\\Roaming\\Reader\\cover"
  resources: "C:\\Users\\Kikki\\AppData\\Roaming\\Reader\\resources"

theme:
  appearance: Light

setting:
  sidebar: True
